### PR TITLE
Scry support for formater,  GoTo definition and other updates

### PR DESCRIPTION
**Pull request by faustinoaq**
Hi @kofno!

I made some changes to improve your project, allowing to use with other plugins and editors. By example, this PR includes [ResponseError](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#response-message) and Position classes made by @keplers for [atom-scry](https://github.com/atom-crystal/scry).

By default is configured for `crystal-ide` but It's easy to configure for others extensions like [vscode-crystal-lang](https://github.com/faustinoaq/vscode-crystal-lang#server-new).

I added more features to Scry. The features are:

- Formatter
- GoTo Definition

There is a screen capture:

ezgif-2-0723b7d6d7

Also, I refactored some files to improve the structure of [Language Server Protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md) specification.

Some screenshots:

screenshot_20170629_221711

screenshot_20170629_221618

screenshot_20170629_210335

screenshot_20170628_115314

Finally I added a logo to your project to be more developer friendly :smile: 

tictft8 - imgur

> Note: Scry is compatible with "vscode-languageclient": "2.2.1" most recent client will need some changes in this server.

### CODE REVIEW

**Comment by kofno** [comment]
Looks good! Let me know when you are ready for a merge!

**Comment by faustinoaq** [comment]
@kofno I didn't sleep, :sweat_smile:  but I found the issue. It was related to `content.size`, it must be `content.bytesize`. See: https://github.com/palantir/python-language-server/issues/25

So, you can merge it now :+1:

**Comment by kofno** [comment]
Done. Thanks again for keeping up with the PRs.

**Comment by keplersj** [comment]
Holy shit. Yes! Perfect! I'll update `atom-crystal` to use this package this weekend. My stuff was largely experimental but this is huge validation.

**Pull request merged**
